import React, { useState } from 'react';
import { useBOEStore } from '../../../store/boeStore';
import { boeVersionsApi } from '../../../services/boeApi';
import BOEWizard from './BOEWizard';

const BOEWizardModal: React.FC = () => {
  const { showWizard, wizardProgramId, currentBOE, closeWizard, setCurrentBOE } = useBOEStore();
  const [isCreating, setIsCreating] = useState(false);

  if (!showWizard || !wizardProgramId) {
    return null;
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-6xl max-h-[90vh] overflow-hidden">
        <div className="p-6 border-b border-gray-200">
          <h2 className="text-xl font-semibold text-gray-900">
            {currentBOE ? 'Create New Version' : 'Create New BOE'}
          </h2>
          <p className="text-gray-600 mt-1">
            {currentBOE 
              ? `Creating new version from ${currentBOE.name} (${currentBOE.versionNumber})`
              : 'Follow the steps below to create a new Basis of Estimate'
            }
          </p>
          {isCreating && (
            <div className="mt-3 p-3 bg-blue-50 border border-blue-200 rounded-md">
              <div className="flex items-center">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600 mr-2"></div>
                <span className="text-blue-800 text-sm">
                  {currentBOE ? 'Creating new version...' : 'Creating BOE...'}
                </span>
              </div>
            </div>
          )}
        </div>
        <div className="p-6 overflow-y-auto max-h-[calc(90vh-120px)]">
          <BOEWizard
            key="centralized-wizard"
            programId={wizardProgramId}
            currentBOE={currentBOE}
            sourceBOE={currentBOE}
            onComplete={async (boeData) => {
              try {
                setIsCreating(true);
                console.log('Creating BOE with data:', boeData);
                
                let newBOE;
                
                // Check if this is a version creation (any method when currentBOE exists) or new BOE creation
                if (currentBOE && boeData.creationMethod) {
                  // Use version creation API for all methods when creating a version
                  const versionData = {
                    creationMethod: 'version-from-current',
                    changeSummary: boeData.changeSummary || 'New version created from existing BOE',
                    wizardData: boeData
                  };
                  
                  const result = await boeVersionsApi.createVersion(wizardProgramId, versionData);
                  newBOE = result.boeVersion;
                  console.log('BOE version created successfully:', newBOE);
                } else {
                  // Use regular BOE creation API
                  const boeCreationData: any = {
                    name: boeData.name,
                    description: boeData.description,
                    // Version number will be auto-generated by backend
                    status: 'Draft'
                  };
                  
                  if (boeData.templateId) {
                    boeCreationData.templateId = boeData.templateId;
                  }
                  
                  if (boeData.elements && boeData.elements.length > 0) {
                    boeCreationData.elements = boeData.elements;
                  }
                  
                  if (boeData.allocations && boeData.allocations.length > 0) {
                    const validAllocations = boeData.allocations.filter((a: any) => 
                      a.startDate && a.endDate && a.totalAmount > 0
                    );
                    if (validAllocations.length > 0) {
                      boeCreationData.allocations = validAllocations;
                    }
                  }
                  
                  newBOE = await boeVersionsApi.createBOE(wizardProgramId, boeCreationData);
                  console.log('BOE created successfully:', newBOE);
                }
                
                // Update the current BOE in the store
                setCurrentBOE(newBOE);
                
                // Close the wizard
                closeWizard();
                
                // Show success message
                alert(currentBOE && boeData.creationMethod 
                  ? 'New BOE version created successfully!' 
                  : 'BOE created successfully!');
                
              } catch (error) {
                console.error('Error creating BOE:', error);
                alert('Error creating BOE. Please try again.');
              } finally {
                setIsCreating(false);
              }
            }}
            onCancel={() => {
              closeWizard();
            }}
          />
        </div>
      </div>
    </div>
  );
};

export default BOEWizardModal; 