version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      args:
        - REACT_APP_API_URL=http://localhost:4000/api
    image: lre_manager_take2-frontend
    container_name: lre_manager_take2-frontend-1
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: lre_manager_take2-backend
    container_name: lre_manager_take2-backend-1
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=lre_manager
      - JWT_SECRET=development_secret
      - JWT_EXPIRATION=24h
      - LOG_LEVEL=info
      - FRONTEND_URL=http://localhost
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: lre_manager_take2-db-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lre_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 