version: '3.8'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:4000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=lre_manager
      - JWT_SECRET=development_secret
      - JWT_EXPIRATION=24h
      - LOG_LEVEL=debug
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ../backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=lre_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 