name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: lre_manager
          POSTGRES_PASSWORD: lre_manager
          POSTGRES_DB: lre_manager_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm ci
        cd frontend && npm ci
        cd ../backend && npm ci

    - name: Lint
      run: |
        npm run lint
        cd frontend && npm run lint
        cd ../backend && npm run lint

    - name: Test
      run: |
        npm test
        cd frontend && npm test
        cd ../backend && npm test
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: lre_manager
        POSTGRES_PASSWORD: lre_manager
        POSTGRES_DB: lre_manager_test
        JWT_SECRET: test_secret
        NODE_ENV: test 